site_name: Python 교육
theme:
  name: material
  language: kr  
  features:
    # - navigation.tabs  
    - navigation.indexes
plugins: []  # 검색을 막아 둠
copyright: Copyright &copy; 2022 (주)퀀트랩
extra:
  generator: false
  analytics:
    provider: google
    property: G-L89YBQ3J9L

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  
nav:
  - 1일차 Python 기초:
    - nano/day1/index.md
    # - Python 소개: python/intro.md
    # - 구글 콜랩: python/colab.md
    # - 아나콘다: python/anaconda.md
    # - 기초 문법: python/basic.md
    # - 엑셀 파일 열기: python/read_excel.md  
  - 2일차 데이터 분석:
    - nano/day2/index.md
  - 3일차:
    - nano/day3/index.md
  - 4일차:
    - nano/day4/index.md
#   - Python:
#   - 회귀분석:
#     - 회귀분석 소개: regression/intro.md
#     - 단순회귀분석: regression/simple.md
#     #- 더미코딩: regression/dummy_coding.md
#     - 다중회귀분석: regression/multiple.md
#     - 독립변수의 표준화: regression/scale.md