import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  statSidebar: [
    {
      type: 'doc',
      id: 'stat/lab',
      label: '실습 및 Q&A'
    },
    {
      type: 'category',
      label: '1일차 - 통계 기초',
      items: [
        {
          type: 'doc',
          id: 'stat/why-learn-statistics',
          label: '통계를 배워야 하는 이유'
        },
        {
          type: 'doc',
          id: 'stat/statistics-and-ai',
          label: '데이터 분석의 종류와 관련 분야'
        },
        {
          type: 'doc',
          id: 'stat/data',
          label: '데이터 수집과 전처리'
        },
        {
          type: 'doc',
          id: 'stat/python',
          label: 'Python'
        },
        {
          type: 'doc',
          id: 'stat/central-tendency',
          label: '기술 통계: 중심경향치'
        },
         {
          type: 'doc',
          id: 'stat/variability',
          label: '기술 통계: 변산성 측정치'
        },
        {
          type: 'doc',
          id: 'stat/distribution',
          label: '분포의 특성과 기술통계'
        },
        {
          type: 'doc',
          id: 'stat/day1-exercise',
          label: '1일차 종합 실습'
        },
      ]
    },
    
    // {
      //   type: 'category',
      //   label: '2일차 - 예측',
      //   items: [
          // {
          //   type: 'doc',
          //   id: 'stat/confidence-interval',
          //   label: '신뢰구간'
          // },
    //     {
    //       type: 'doc',
    //       id: 'stat/hypothesis-testing',
    //       label: '통계적 가설 검정'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/correlation',
    //       label: '상관 분석'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/regression',
    //       label: '회귀 분석'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/multiple-regression',
    //       label: '다중 회귀 분석'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/variable-transformation',
    //       label: '변수의 변형'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/day2-exercise',
    //       label: '2일차 종합 실습'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/model-selection',
    //       label: '모형 선택'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/interaction',
    //       label: '상호작용'
    //     },
    //   ]
    // },
    // {
    //   type: 'category',
    //   label: '3일차 - 머신러닝',
    //   items: [
    //     {
    //       type: 'doc',
    //       id: 'stat/supervised-learning-classification',
    //       label: '지도학습 - 분류'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/supervised-learning-regression',
    //       label: '지도학습 - 회귀'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/unsupervised-learning-clustering',
    //       label: '비지도학습 - 클러스터링'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/unsupervised-learning-dimension-reduction',
    //       label: '비지도학습 - 차원 축소'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/day3-exercise',
    //       label: '3일차 종합 실습'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/reinforcement-learning',
    //       label: '강화학습'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/deep-learning',
    //       label: '딥러닝'
    //     },
    //   ]
    // },
    // {
    //   type: 'category',
    //   label: '4일차 - 시계열 분석',
    //   items: [
    //     {
    //       type: 'doc',
    //       id: 'stat/time-series',
    //       label: '시계열 데이터 분석의 소개'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/python-time-series',
    //       label: 'Python으로 시계열 데이터 다루기'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/autocorrelation',
    //       label: '자기 상관'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/time-series-prediction',
    //       label: '시계열 예측'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/time-series-clustering',
    //       label: '시계열 클러스터링'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/survival-analysis',
    //       label: '생존 분석'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/day4-exercise',
    //       label: '4일차 종합 실습'
    //     },
    //   ]
    // },
    // {
    //   type: 'category',
    //   label: '5일차 - 텍스트 분석',
    //   items: [
    //     {
    //       type: 'doc',
    //       id: 'stat/text-analysis',
    //       label: '텍스트 데이터 분석 소개'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/document-term-matrix',
    //       label: '단어 통계'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/tokenization',
    //       label: '형태소 분석'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/topic-modeling',
    //       label: '토픽 모델링'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/text-classification',
    //       label: '문서 분류'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/language-models',
    //       label: '언어 모형과 생성형 인공지능'
    //     },
    //     {
    //       type: 'doc',
    //       id: 'stat/day5-exercise',
    //       label: '5일차 종합 실습'
    //     },
    //   ]
    // },
  ],
  reinforcementLearningSidebar: [
    {
      type: 'doc',
      id: 'reinforcement-learning/lab',
      label: '실습 및 Q&A'
    },
    {
      type: 'category',
      label: '1일차 - 기본 개념',
      items: [
        {
          type: 'doc',
          id: 'reinforcement-learning/intro',
          label: '시작하기'
        },
        {
          type: 'doc',
          id: 'reinforcement-learning/what-is',
          label: '강화학습이란 무엇인가'
        },
        {
          type: 'doc',
          id: 'reinforcement-learning/terms',
          label: '기본 용어'
        },
        {
          type: 'doc',
          id: 'reinforcement-learning/gym',
          label: 'gymnasium'
        },
        // {
        //   type: 'doc',
        //   id: 'reinforcement-learning/discount',
        //   label: '할인'
        // },
        {
          type: 'doc',
          id: 'reinforcement-learning/value',
          label: '가치'
        },
      ],
    },
    {
      type: 'category',
      label: '2일차 - 추정과 탐색',
      items: [
        {
          type: 'doc',
          id: 'reinforcement-learning/dynamic-programming',
          label: '동적 계획법'
        },
        {
          type: 'doc',
          id: 'reinforcement-learning/bootstrap',
          label: '부트스트랩'
        },
        {
          type: 'doc',
          id: 'reinforcement-learning/multi-armed-bandit',
          label: 'MAB'
        },
        {
          type: 'doc',
          id: 'reinforcement-learning/monte-carlo',
          label: '몬테카를로'
        },
      ]
    },
    {
      type: 'category',
      label: '3일차 - 제어와 딥러닝',
      items: [
        {
          type: 'doc',
          id: 'reinforcement-learning/temporal-difference',
          label: '시간차 학습'
        },
        {
          type: 'doc',
          id: 'reinforcement-learning/control-problem',
          label: '제어 문제'
        },
        {
          type: 'doc',
          id: 'reinforcement-learning/deep-learning',
          label: '딥러닝'
        },
      ]
    },
    {
      type: 'category',
      label: '4일차 - 심층 강화학습',
      items: [
        {
          type: 'doc',
          id: 'reinforcement-learning/dqn',
          label: '가치 기반 강화 학습'
        },
        {
          type: 'doc',
          id: 'reinforcement-learning/replay',
          label: '경험 리플레이'
        },
        {
          type: 'doc',
          id: 'reinforcement-learning/policy-gradient',
          label: '정책 경사'
        },
        {
          type: 'doc',
          id: 'reinforcement-learning/actor-critic',
          label: 'Actor-Critic'
        },
        {
          type: 'doc',
          id: 'reinforcement-learning/application',
          label: '실무 적용 방안'
        },
      ]
    },
    {
      type: 'category',
      label: '5일차 - 최근 동향',
      items: [
        {
          type: 'doc',
          id: 'reinforcement-learning/ship-control',
          label: '[사례] 선박 제어'
        },
        {
          type: 'doc',
          id: 'reinforcement-learning/ppo',
          label: 'PPO'
        },
        {
          type: 'doc',
          id: 'reinforcement-learning/off-policy-policy-gradient',
          label: 'off-policy 정책 경사'
        },
        {
          type: 'doc',
          id: 'reinforcement-learning/mcts',
          label: '알파고'
        },
        {
          type: 'doc',
          id: 'reinforcement-learning/other-methods',
          label: '다른 방법들'
        },
        {
          type: 'doc',
          id: 'reinforcement-learning/chatbot',
          label: '챗봇'
        },
        {
          type: 'doc',
          id: 'reinforcement-learning/challenges',
          label: '문제점'
        },
      ]
    },
  ],
  machineLearningSidebar: [
    { type: 'doc',
      id: 'machine-learning/lab',
      label: '실습 및 Q&A'
    },
    { type: 'doc',
      id: 'machine-learning/intro',
      label: '시작하기'
    },
    { type: 'doc',
      id: 'machine-learning/preprocessing',
      label: '데이터 클리닝 및 전처리 기법'
    },
    // { type: 'doc',
    //   id: 'machine-learning/recent-trends',
    //   label: '머신러닝 기법의 최근 동향'
    // },
    { type: 'doc',
      id: 'machine-learning/eda',
      label: '탐색적 데이터 분석'
    },
    { type: 'doc',
      id: 'machine-learning/imbalanced',
      label: '불균형한 데이터의 처리'
    },
    // { type: 'doc',
    //   id: 'machine-learning/augmentation',
    //   label: '데이터 증강'
    // },
    { type: 'doc',
      id: 'machine-learning/time-series',
      label: '시계열 분석 프로젝트 사례 연구'
    },
    { type: 'doc',
      id: 'machine-learning/tabpfn',
      label: '표(tabular) 데이터의 머신러닝'
    },
    // { type: 'doc',
    //   id: 'machine-learning/unstructured',
    //   label: '비정형 데이터의 머신 러닝'
    // },
    // { type: 'doc',
    //   id: 'machine-learning/weak-supervision',
    //   label: '불완전한 데이터의 약한 지도'
    // },
    { type: 'doc',
      id: 'machine-learning/hyperparameter-tuning',
      label: '하이퍼파라미터 튜닝'
    },
    { type: 'doc',
      id: 'machine-learning/confusion-matrix',
      label: '모델 성능 비교 및 선택 전략'
    },
    // { type: 'doc',
    //   id: 'machine-learning/computer-vision',
    //   label: '컴퓨터 비전 사례 연구'
    // },
    { type: 'doc',
      id: 'machine-learning/ensemble',
      label: '앙상블'
    },
    { type: 'doc',
      id: 'machine-learning/xAI',
      label: '설명가능한 AI'
    },
    { type: 'doc',
      id: 'machine-learning/generative-ai',
      label: '생성형 AI'
    },
    { type: 'doc',
      id: 'machine-learning/nlg',
      label: '자연어 생성'
    },
    { type: 'doc',
      id: 'machine-learning/nlp',
      label: '자연어 처리 프로젝트 사례 연구'
    },
  ],
  computerVisionSidebar: [
    { type: 'doc',
      id: 'computer-vision/lab',
      label: '실습 및 Q&A'
    },
    // 이하는 아직 수업 안해서 가려놓은 부분
    // { type: 'doc',
    //   id: 'computer-vision/questionaire',
    //   label: '설문'
    // },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/tasks',
    //   label: '컴퓨터 비전 과업'
    // },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/PIL-note',
    //   label: 'PIL'
    // },
    // { type: 'doc',
    //   id: 'computer-vision/opencv',
    //   label: 'OpenCV 기초'
    // },
    // { type: 'doc',
    //   id: 'computer-vision/image-operation',
    //   label: '이미지 연산'
    // },
    // { type: 'doc',
    //   id: 'computer-vision/color',
    //   label: '색 보정'
    // },
    {
      type: 'doc',
      id: 'computer-vision/day1-review',
      label: '1일차 복습'
    },
    // { type: 'doc',
    //   id: 'computer-vision/lut',
    //   label: '룩업 테이블'
    // },
    // { type: 'doc',
    //   id: 'computer-vision/image-transform',
    //   label: '이미지 변형'
    // },
    // { type: 'doc',
    //   id: 'computer-vision/camera-calibration',
    //   label: '카메라 교정'
    // },
    // { type: 'doc',
    //   id: 'computer-vision/filter',
    //   label: '필터링'
    // },
    // { type: 'doc',
    //   id: 'computer-vision/shape',
    //   label: '모양 감지'
    // },
    // { type: 'doc',
    //   id: 'computer-vision/match',
    //   label: '이미지 매칭'
    // },
    {
      type: 'doc',
      id: 'computer-vision/day2-review',
      label: '2일차 복습'
    },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/feature-detector',
    //   label: '특징 검출'
    // },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/deep-learning',
    //   label: '컴퓨터 비전과 딥러닝'
    // },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/frameworks',
    //   label: '딥러닝 프레임워크'
    // },
    // {
    //     type: 'doc',
    //     id: 'computer-vision/binary-classification',
    //     label: '이미지 이항 분류'
    // },
    // {
    //     type: 'doc',
    //     id: 'computer-vision/confusion-matrix',
    //     label: '혼동 행렬'
    // },
    {
      type: 'doc',
      id: 'computer-vision/day3-review',
      label: '3일차 복습'
    },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/MLP',
    //   label: '다층 신경망'
    // },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/lightning',
    //   label: 'PyTorch Lightning'
    // },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/hyperparameter-tuning',
    //   label: '하이퍼파라미터 튜닝'
    // },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/multiclass',
    //   label: '다항 분류'
    // },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/cnn',
    //   label: '합성곱 신경망'
    // },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/augmentation',
    //   label: '데이터 증강'
    // },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/vit',
    //   label: '비전 트랜스포머'
    // },
    {
      type: 'doc',
      id: 'computer-vision/day4-review',
      label: '4일차 복습'
    },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/transfer-learning',
    //   label: '전이 학습'
    // },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/object-detection',
    //   label: '물체 탐지'
    // },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/annotation',
    //   label: '데이터 만들기'
    // },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/autoencoder',
    //   label: '오토인코더'
    // },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/embedding',
    //   label: '임베딩'
    // },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/multi-modal',
    //   label: '멀티 모달'
    // },
    // {
    //   type: 'doc',
    //   id: 'computer-vision/generation',
    //   label: '생성'
    // },
    // 이하는 DEPRECATED
    // { type: 'doc',
    //   id: 'computer-vision/PIL',
    //   label: 'Python 이미지 처리'
    // },
    // {
    //     type: 'doc',
    //     id: 'computer-vision/gradient-descent',
    //     label: '손실 함수와 경사하강법'
    // },
    // {
    //     type: 'doc',
    //     id: 'computer-vision/application-ideas',
    //     label: '실무 적용 방안'
    // }
  ],
  timeSeriesSidebar: [
    { type: 'doc',
      id: 'time-series/intro',
      label: '실습 및 Q&A'
    },
    { type: 'doc',
      id: 'time-series/pandas',
      label: 'pandas에서 날짜/시간 다루기'
    },
    { type: 'doc',
      id: 'python-data-science/file-format',
      label: '파일 포맷'
    },
    {
      type: 'doc',
      id: 'time-series/correlation',
      label: '상관'
    },
    {
      type: 'doc',
      id: 'time-series/unit-root-test',
      label: '단위근 검정'
    },
    {
      type: 'doc',
      id: 'time-series/simple-forecasting',
      label: '시계열의 패턴과 예측'
    },
    {
      type: 'doc',
      id: 'time-series/review2',
      label: '2일차 복습 ★'
    },
    {
      type: 'doc',
      id: 'time-series/review2-solution',
      label: '2일차 복습 풀이'
    },
    {
      type: 'doc',
      id: 'time-series/regression',
      label: '회귀분석'
    },
    {
      type: 'doc',
      id: 'time-series/time-series-regression',
      label: '시계열 회귀'
    },
    {
      type: 'doc',
      id: 'time-series/decomposition',
      label: '시계열 분해'
    },
    {
      type: 'doc',
      id: 'time-series/review3',
      label: '3일차 복습 ★'
    },
    {
      type: 'doc',
      id: 'time-series/review3-solution',
      label: '3일차 복습 풀이'
    },
    {
      type: 'doc',
      id: 'time-series/ETS',
      label: '지수 평활'
    },
    {
      type: 'doc',
      id: 'time-series/clustering',
      label: '클러스터링'
    },
    {
      type: 'doc',
      id: 'time-series/temporal-fusion-transformers',
      label: 'Temporal Fusion Transformers'
    }
  ],
  nlpSidebar: [
    { type: 'doc',
      id: 'nlp/what-is-nlp',
      label: '자연어 처리 소개'
    },
    {
      type: 'doc',
      id: 'nlp/nlp-tasks',
      label: '자연어 처리의 주요 과제'
    },
    {
      type: 'doc',
      id: 'nlp/document-term-matrix',
      label: '문서 단어 행렬'
    },
    {
      type: 'doc',
      id: 'nlp/word-cloud',
      label: '단어 구름'
    },
    {
      type: 'doc',
      id: 'nlp/tokenization',
      label: '토큰화'
    },
    {
      type: 'doc',
      id: 'nlp/encoding',
      label: '인코딩'
    },
    {
      type: 'doc',
      id: 'nlp/day1-review',
      label: '★ 1일차 복습'
    },
    {
      type: 'doc',
      id: 'nlp/cooccurence',
      label: '공기어 네트워크'
    },
    {
      type: 'doc',
      id: 'nlp/whisper',
      label: '음성 인식'
    },
    {
      type: 'doc',
      id: 'nlp/similarity',
      label: '거리와 유사도'
    },
    {
      type: 'doc',
      id: 'nlp/embedding',
      label: '임베딩'
    },
    {
      type: 'doc',
      id: 'nlp/clustering',
      label: '문서 클러스터링'
    },
    {
      type: 'doc',
      id: 'nlp/day2-review',
      label: '★ 2일차 복습'
    },
    {
      type: 'doc',
      id: 'nlp/bert',
      label: 'BERT를 이용한 키워드 추출'
    },
    {
      type: 'doc',
      id: 'nlp/keyword-search',
      label: '키워드 검색'
    },
    {
      type: 'doc',
      id: 'nlp/vector-search',
      label: '벡터 검색'
    },
    {
      type: 'doc',
      id: 'nlp/classification',
      label: '문서 분류'
    },
    {
      type: 'doc',
      id: 'nlp/deep-learning',
      label: '딥러닝'
    }
  ]
};

export default sidebars;
